## Pandas Cheat Sheet

From the Complete Python Pandas Data Science Tutorial! (2025 Updated Edition) https://www.youtube.com/watch?v=2uvysYbKdjM a cheat sheet.

In [73]:
pip install pandas numpy matplotlib seaborn scikit-learn pyarrow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.6)
Requirement already satisfied: numpy in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.5.3)
Requirement already satisfied: matplotlib in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.11.2)
Requirement already satisfied: seaborn in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.9.1)
Requirement already satisfied: pyarrow in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (25.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in C:\Users\James\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

####
- **Series**: One dimensional labeled array.
- **DataFrame**: Two dimensional table structure.

- Inspection methods:
    - df.head(n) views top rows.
    - df.tail(n) views bottom rows.
    - df.sample(n) gets random rows.
    - df.info() checks types, nulls, memory.
    - df.describe() shows statistical summaries.
    - df.shape checks dimensions.
    - df.size counts total items.

In [74]:
import pandas as pd
import numpy as np

# one dimensional array
scores = pd.Series([88, 92, 75, 61, 95],
                   index=['alice', 'bob', 'carol', 'dave', 'erin'],
                   name='score')
scores

# two dimensional table structure
df = pd.DataFrame({
    'product': ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard'],
    'category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Accessories'],
    'price': [1200, 800, 450, 300, 60],
    'units_sold': [12, 40, 25, 18, 100]
})
df

# methods
df.head(3)     # top rows
df.tail(2)     # bottom rows
df.sample(2)   # random rows
df.info()      # types, nulls, memory
df.describe()  # statistical summaries
df.shape       # dimensions
df.size        # total number of items
# or this to decribe type
scores.describe()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     5 non-null      str
 1   category    5 non-null      str
 2   price       5 non-null      int64
 3   units_sold  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

count     5.000000
mean     82.200000
std      14.096099
min      61.000000
25%      75.000000
50%      88.000000
75%      92.000000
max      95.000000
Name: score, dtype: float64

#### Input and Output
- **CSV files**: pd.read_csv('path.csv')
- **Excel files**: pd.read_excel('path.xlsx', sheet_name='Sheet1')
- **Parquet or Feather files**: pd.read_parquet('path.parquet') for speed.
- **Exporting data**: df.to_csv('path.csv', index=False)

#### Data Access and Indexing
- **Column access**: df['col_name'] or df.col_name
- **Label indexing**: df.loc[]
- **Integer position indexing**: df.iloc[]
- **Fast scalar lookup**: df.at[] and df.iat[]
- **Sorting**: df.sort_values(by='col', ascending=False)

In [75]:
# Column access
df['product']
df.price # attribute

# Label indexing
df.loc[0:2, ['product', 'price']]

# Integer indexing
df.iloc[0:3, 1:3]

# Fast scalar lookup
df.at[0, 'product'] # by label
df.iat[0, 1] # by position

# Sorting
df.sort_values(by='price', ascending=False)

    product     category  price  units_sold
0    Laptop  Electronics   1200          12
1     Phone  Electronics    800          40
2    Tablet  Electronics    450          25
3   Monitor  Electronics    300          18
4  Keyboard  Accessories     60         100

#### Filtering Data
- **Boolean indexing**: df[df['col'] > value]
- **Multiple conditions**: use parentheses and & or |
- **String operations**: df['col'].str.contains('pattern', case=False)
- **String matching**: df['col'].str.startswith() or df['col'].isin([...])

In [76]:
# Boolean indexing
df[df['price'] > 400]
df[(df['price'] > 400) & (df['units_sold'] > 20)]
df[(df['category'] == 'Accessories') | (df['price'] > 1000)]

# String 
df[df['product'].str.contains('phone', case=False)]
df[df['product'].str.startswith('T')]
df[df['category'].isin(['Electronics', 'Accessories'])]

    product     category  price  units_sold
0    Laptop  Electronics   1200          12
1     Phone  Electronics    800          40
2    Tablet  Electronics    450          25
3   Monitor  Electronics    300          18
4  Keyboard  Accessories     60         100

#### Column Manipulation
- **Adding columns**: df['new_col'] = df['col1'] * df['col2']
- **Conditional assignment**: np.where(condition, true_val, false_val)
- **Renaming columns**: df.rename(columns={'old': 'new'}, inplace=True)
- **Dropping columns**: df.drop(columns=['col_name'], inplace=True)
- **Copying data**: df.copy()

In [77]:
# Adding columns
df['revenue'] = df['price'] * df['units_sold']
df['tier'] = np.where(df['revenue'] > 15000, 'High', 'Standard')
df.rename(columns={'tier': 'value_tier'}, inplace=True)
data = df.copy()
df.drop(columns=['value_tier'], inplace=True)
data

    product     category  price  units_sold  revenue value_tier
0    Laptop  Electronics   1200          12    14400   Standard
1     Phone  Electronics    800          40    32000       High
2    Tablet  Electronics    450          25    11250   Standard
3   Monitor  Electronics    300          18     5400   Standard
4  Keyboard  Accessories     60         100     6000   Standard

#### Datetime Operations
- **Conversion**: pd.to_datetime()
- **Extraction**: df['date_col'].dt.year, df['date_col'].dt.month, df['date_col'].dt.day_of_week

In [78]:
orders = pd.DataFrame({
    'order_id': [1, 2, 3, 4],
    'date': ['2024-01-15', '2024-01-29', '2024-02-03', '2024-02-18'],
    'sales': [120.50, 80.00, 200.00, 65.25]
})

# Conversion
orders['date'] = pd.to_datetime(orders['date'])
orders['date'].dtype

# Extraction
orders['year'] = orders['date'].dt.year
orders['month'] = orders['date'].dt.month
orders['day_of_week'] = orders['date'].dt.day_of_week
orders

   order_id       date   sales  year  month  day_of_week
0         1 2024-01-15  120.50  2024      1            0
1         2 2024-01-29   80.00  2024      1            0
2         3 2024-02-03  200.00  2024      2            5
3         4 2024-02-18   65.25  2024      2            6

#### Custom Functions
- **Apply method**: df.apply(lambda x: ..., axis=1)

In [79]:
# run a function on every row
df.apply(lambda row: row['price'] * row['units_sold'], axis=1)

# using a named function
def revenue_band(revenue):
    return 'high' if revenue > 15000 else 'low'

df['revenue_band'] = df.apply(lambda row: revenue_band(row['revenue']), axis=1)
df

    product     category  price  units_sold  revenue revenue_band
0    Laptop  Electronics   1200          12    14400          low
1     Phone  Electronics    800          40    32000         high
2    Tablet  Electronics    450          25    11250          low
3   Monitor  Electronics    300          18     5400          low
4  Keyboard  Accessories     60         100     6000          low

#### Merging and Concatenating
- **Merging datasets**: pd.merge(df1, df2, left_on='a', right_on='b', how='left')
- **Concatenating datasets**: pd.concat([df1, df2])

In [80]:
targets = pd.DataFrame({
    'item': ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard'],
    'sales_target': [150, 400, 300, 200, 90]
})

# Merging data
pd.merge(df, targets, left_on='product', right_on='item', how='left')

# Concatenation data
pd.concat([df.iloc[:2], df.iloc[2:]])

    product     category  price  units_sold  revenue revenue_band
0    Laptop  Electronics   1200          12    14400          low
1     Phone  Electronics    800          40    32000         high
2    Tablet  Electronics    450          25    11250          low
3   Monitor  Electronics    300          18     5400          low
4  Keyboard  Accessories     60         100     6000          low

#### Handling Missing Values
- **Detection**: df.isna().sum()
- **Imputation**: df.fillna(value) or df.interpolate()
- **Dropping nulls**: df.dropna(subset=['col'])

In [81]:
missing = df.copy()
missing.loc[1, 'price'] = np.nan
missing.loc[3, 'units_sold'] = np.nan

# Detection
missing.isna().sum()

# Imputation
missing['price'].fillna(missing['price'].mean())
missing['units_sold'] = missing['units_sold'].fillna(0)
missing['price'] = missing['price'].interpolate()
missing

# Dropping nulls
missing.dropna(subset=['price'])

    product     category   price  units_sold  revenue revenue_band
0    Laptop  Electronics  1200.0        12.0    14400          low
1     Phone  Electronics   825.0        40.0    32000         high
2    Tablet  Electronics   450.0        25.0    11250          low
3   Monitor  Electronics   300.0         0.0     5400          low
4  Keyboard  Accessories    60.0       100.0     6000          low

#### Aggregation and Grouping
- **Value counts**: df['col'].value_counts()
- **Group by**: df.groupby('col').agg({'col1': 'sum'})
- **Pivot tables**: df.pivot_table(index='col1', columns='col2', values='col3', aggfunc='sum')

In [82]:
# Value counts
df['category'].value_counts()

# Group by
df.groupby('category').agg({'units_sold': 'sum', 'revenue': 'mean'})

# Pivot tables
df.pivot_table(index='category', columns='product', values='revenue', aggfunc='sum')
regions = pd.DataFrame({
    'product': ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard'],
    'region': ['North', 'South', 'North', 'South', 'North']
})
with_region = pd.merge(df, regions, on='product', how='inner')
with_region.pivot_table(index='category', columns='region', values='revenue', aggfunc='sum')

region         North    South
category
Accessories   6000.0      NaN
Electronics  25650.0  37400.0

- **Shifting**: df['col'].shift(n)
- **Rolling windows**: df['col'].rolling(window=n).sum()
- **Ranking**: df['col'].rank(ascending=False)
- **PyArrow backend**: modern performance optimization for strings

In [83]:
import importlib.util
import pandas as pd
import pyarrow

daily = orders.sort_values('date').reset_index(drop=True)
daily['prev_sales'] = daily['sales'].shift(1)
daily['sales_change'] = daily['sales'] - daily['sales'].shift(1)
daily['rolling_sum'] = daily['sales'].rolling(window=2).sum()
daily['rolling_mean'] = daily['sales'].rolling(window=2).mean()
daily['sales_rank'] = daily['sales'].rank(ascending=False)
print(daily.dtypes)

order_id                 int64
date            datetime64[us]
sales                  float64
year                     int32
month                    int32
day_of_week              int32
prev_sales             float64
sales_change           float64
rolling_sum            float64
rolling_mean           float64
sales_rank             float64
dtype: object

---

## Analysis Questions

- **Question**: Which category generated the highest total revenue?

In [84]:
# Group data
revenue_by_category = df.groupby('category')['revenue'].sum()
revenue_by_category

# getting the highest total revenue
revenue_by_category.idxmax()
revenue_by_category.max()

np.int64(63050)

- **Answer**: Group data by category and aggregate total sales. Example: df.groupby('category')['revenue'].sum()

---

- **Question**: How do sales in January compare to February?

In [85]:
# Parse dates
monthly_sales = orders.groupby(orders['date'].dt.month)['sales'].sum()
monthly_sales

january = monthly_sales.loc[1]
february = monthly_sales.loc[2]

print(f"January total:   {january:.2f}")
print(f"February total:  {february:.2f}")
print(f"Difference:      {february - january:+.2f}")

January total:   200.50
February total:  265.25
Difference:      +64.75

- **Answer**: Parse dates, filter by month, and compare sums or use shift. Example: df.groupby(df['date'].dt.month)['sales'].sum()

---

- **Question**: Are there missing values or anomalies in specific columns?

In [86]:
check = orders.copy()
check.loc[1, 'sales'] = np.nan
# Count missing entries
check.isna().sum()
check['sales'].describe()

# Values more than 2 standard deviations
threshold = check['sales'].mean() + 2 * check['sales'].std()
check[check['sales'] > threshold]

Empty DataFrame
Columns: [order_id, date, sales, year, month, day_of_week]
Index: []

- **Answer**: Count missing entries and review summary statistics. Example: df.isna().sum() and df.describe()

---

- **Question**: How do two separate datasets relate to each other?

In [87]:
# second dataset
regions = pd.DataFrame({
    'product': ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard'],
    'region': ['North', 'South', 'North', 'South', 'North']
})
# Combine them with a shared key
combined = pd.merge(df, regions, on='product', how='inner')
combined
# Relate the joined data further
combined.groupby('region')['revenue'].sum()

region
North    31650
South    37400
Name: revenue, dtype: int64

- **Answer**: Combine them using a shared key. Example: pd.merge(df1, df2, on='common_id', how='inner')